# Generated by Django 2.1 on 2018-10-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='isRead',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phonelist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phonelist',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phonelist',
            name='star',
            field=models.CharField(default='普通', max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='callLength',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='callTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='digits',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='template_store',
            name='cid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='template_store',
            name='flag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='template_store',
            name='pos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='template_store',
            name='vid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='templates',
            name='tname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
